openapi: 3.0.3
info:
  title: Go Base Microservice
  description: A minimal Go microservice template with PostgreSQL, Kafka, and Kubernetes health endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

components:
  schemas:
    HealthCheck:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
        timestamp:
          type: string
          format: date-time
        details:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: string
              error:
                type: string
    
    VersionInfo:
      type: object
      properties:
        version:
          type: string
          example: v1.0.0
        commit:
          type: string
          example: abc123def456
        date:
          type: string
          example: "2024-01-01T00:00:00Z"
        built_by:
          type: string
          example: goreleaser
    
    LogLevel:
      type: object
      properties:
        level:
          type: string
          enum: [debug, info, warn, error]
          example: info
    
    LogLevelRequest:
      type: object
      required: [level]
      properties:
        level:
          type: string
          enum: [debug, info, warn, error]
          example: debug
    
    LogLevelResponse:
      type: object
      properties:
        level:
          type: string
          example: debug
        message:
          type: string
          example: Log level updated successfully
    
    Error:
      type: object
      properties:
        error:
          type: string
          example: Invalid request

tags:
  - name: Health
    description: Health check endpoints
  - name: Info
    description: Information endpoints
  - name: Admin
    description: Administrative endpoints
  - name: API
    description: Application API endpoints